[build-system]
requires = ["setuptools>=42", "wheel", "platformdirs>=3.11.0", "numpy", "tqdm", "ffmpeg-python", "blender-stubs"]
build-backend = "setuptools.build_meta"

[project]
name = "blendersynth"
version = "0.3.2"
authors = [
  { name="Ollie Boyne", email="ollieboyne@gmail.com" },
]
description = "Synthetic Rendering for Blender"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "platformdirs>=3.11.0",
    "numpy",
    "tqdm",
    "ffmpeg-python",
    "blender-stubs"
]

[dependency-groups]
dev = [
    "pip>=26.0.1",
]

[project.urls]
"Homepage" = "https://github.com/OllieBoyne/BlenderSynth"
