name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx_rtd_theme
          pip install m2r2
          pip install appdirs
          pip install numpy
          pip install tqdm
          pip install ffmpeg-python
          pip install sphinx_autodoc_typehints
          pip install git+https://github.com/sphinx-contrib/googleanalytics

      - name: Build docs
        run: |
          chmod +x ./docs/build_docs.sh
          ./docs/build_docs.sh

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: .deploy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy docs to gh-pages branch
        run: cp -r docs/_build/* .deploy/

      - name: Commit and push
        run: |
          cd .deploy
          git config user.email "action@github.com" --local
          git config user.name "GitHub Action" --local
          git add .
          git commit -m "Update documentation" -a || true
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OllieBoyne/BlenderSynth.git
          git push origin gh-pages --force
